name: Generate workflows check

on:
  pull_request:
    branches: [ master ]

jobs:
  generate-workflows-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: File extensions set properly
        # error if there are any files in the directory that do not have the
        # .yaml extension.
        run: |
          nonYamlFiles="$(ls .github/workflows/ | grep -v "yaml")"
          if [[ -n "$nonYamlFiles" ]]; then
               echo "Found non-yaml files in .github/workflows/:"
               echo $nonYamlFiles
			   exit 1
          fi
      - uses: actions/setup-go@v2
      - name: Run script
        run: go run scripts/generate-workflows.go
      - name: Check diff
        run: |
          if [[ -n "$(git diff .github/workflows)" ]]; then
              echo "Unexpected differences in the .github/workflows directory:"
              git diff .github/workflows
              echo ""
              echo "Run ./scripts/generate-workflows.go from the repo root and commit the results."
              exit 1
          fi
