name: golang-comments-service test
on:
  pull_request:
    branches: [ master ]

jobs:
  golang-comments-service-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Test
        # Evidently we can't 'go test apps/comments-service/...' or the go tool will
        # search GOPATH instead of the module at apps/comments-service.
        run: cd apps/comments-service && go test -v ./...
