name: Merge
on:
  push:
    branches: [40-lambda-support]
jobs:
  actionize_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Go setup
        uses: actions/setup-go@v2
      - name: Go test
        run: (cd apps/actionize && go test -v ./...)
  actionize_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Go setup
        uses: actions/setup-go@v2
      - name: Fetch golint
        run: |-
          (
              cd apps/actionize &&
              mkdir bin &&
              export GOBIN=$PWD/bin &&
              echo "GOBIN=$GOBIN" >> $GITHUB_ENV &&
              go get golang.org/x/lint/golint
          )
      - name: Go lint
        run: (cd apps/actionize && golint ./...)
  bootstrap-tf_fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Terraform setup
        uses: hashicorp/setup-terraform@v1
      - name: Terraform fmt
        run: terraform -chdir=targets/bootstrap fmt -recursive -check
  bootstrap-tf_apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Terraform setup
        uses: hashicorp/setup-terraform@v1
      - name: Terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
        run: terraform -chdir=targets/bootstrap init
      - name: Terraform apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
        run: terraform -chdir=targets/bootstrap apply
  lambda-support_fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Terraform setup
        uses: hashicorp/setup-terraform@v1
      - name: Terraform fmt
        run: terraform -chdir=targets/lambda-support fmt -recursive -check
  lambda-support_apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Terraform setup
        uses: hashicorp/setup-terraform@v1
      - name: Terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
        run: terraform -chdir=targets/lambda-support init
      - name: Terraform apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
        run: terraform -chdir=targets/lambda-support apply
