name: Terraform format check

on:
  pull_request:
    branches: [ master ]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Terraform setup
        uses: hashicorp/setup-terraform@v1
      - name: Terraform format check
        run: |
          tfDirs="$(for file in $(find . -name \*.tf); do dirname $file; done | sort | uniq)"
          for dir in $tfDirs; do
            terraform fmt -check $dir
            # If there is an error, we want to note it and keep going because
            # we want to print the complete list of files with formatting
            # errors before exiting. We'll exit with a failure when we've
            # finished.
            if [[ "$?" != 0 ]]; then
              failed="true"
            fi
          done

          # If there was a failure, exit accordingly
          if [[ -n "$failed" ]]; then
            exit 1
          fi
