name: Pull Request
on:
  pull_request:
    branches: [40-lambda-support]
jobs:
  bootstrap-tf-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - name: lint-terraform
        run: terraform -chdir=targets/bootstrap fmt -recursive -check
  bootstrap-tf-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - name: Terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
        run: terraform -chdir=targets/bootstrap init
      - name: plan-terraform
        run: terraform -chdir=targets/bootstrap fmt -recursive -check-service
